### ISSUE TITLE
Not login how days... 

### ISSUE THREAD

**Issue by Ankur4299** [orlandodiaz/insta_api#2]
''' code'''
from insta_api import insta_api
import time

insta = InstaAPI()
insta.logout()
time.sleep(3)
insta.login("nasbandikoroali", "menhibatara")

'''output'''
Traceback (most recent call last):
  File "E:/Ankur 2019/Projects/insta_Bot/For another pc/Insta_log.py", line 4, in <module>
    insta = insta_api.InstaAPI()
  File "C:\Program Files\Python37\lib\site-packages\insta_api\insta_api.py", line 63, in __init__
    self.get_username()
  File "C:\Program Files\Python37\lib\site-packages\insta_api\utils.py", line 11, in wrapper
    return fn(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\insta_api\insta_api.py", line 73, in get_username
    user_info = resp.json()['form_data']
  File "C:\Program Files\Python37\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\simplejson\__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python37\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Program Files\Python37\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "C:\Program Files\Python37\lib\site-packages\simplejson\scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "C:\Program Files\Python37\lib\site-packages\simplejson\scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by orlandodiaz** [comment]
Instagram updated their API. Should be good now

**Comment by Btibert3** [comment]
The same issue is happening for me again.
