### ISSUE TITLE
Unable to import insta_api

### ISSUE THREAD

**Issue by ThisIsNoahEvans** [orlandodiaz/insta_api#3]
Hi, as soon as I import `insta_api` to my Python file I'm getting this error:

```
Traceback (most recent call last):
  File "/Users/noah/Local Documents/instagram.py", line 1, in <module>
    from insta_api import insta_api
  File "/opt/homebrew/lib/python3.9/site-packages/insta_api/__init__.py", line 1, in <module>
    from .insta_api import InstaAPI
  File "/opt/homebrew/lib/python3.9/site-packages/insta_api/insta_api.py", line 8, in <module>
    from log3 import log
  File "/opt/homebrew/lib/python3.9/site-packages/log3/__init__.py", line 1, in <module>
    from .log import logger as log
  File "/opt/homebrew/lib/python3.9/site-packages/log3/log.py", line 31, in <module>
    config()
  File "/opt/homebrew/lib/python3.9/site-packages/log3/log.py", line 22, in config
    formatter = logging.Formatter(fmt, datefmt=date_fmt)
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 570, in __init__
    self._style.validate()
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 422, in validate
    if not self.validation_pattern.search(self._fmt):
TypeError: expected string or bytes-like object
```

I am using one of the new M1 Macs, so it might be that? Running with a Rosetta version of Terminal also gives this error, though. macOS Big Sur 11.2. 
I've got an Ubuntu machine I could try it on if you think that's the issue. 

Thanks! :)

**Comment by remictrr** [comment]
Yeah i have the same problem i think it might come from your python version. I see you are using python 3.9, and I myself use python 3.8. Maybe using an older version like 3.6 or even 3.5 might work. I will try this if i have the time to...

**Comment by RaddedMC** [comment]
I'm using Python 3.8.6 and am having the same issue. Windows 10 build 20H2.

**Comment by Alirezakhg** [comment]
+1

**Comment by Demmenie** [comment]
I don't know if this issue was explicitly resolved but I have no issues installing with Python 3.10.2

**Comment by Demmenie** [comment]
This is a longstanding issue with log3, nothing we can really do to fix it at this end other than to remove log3 as a dependency.

**Comment by Demmenie** [comment]
Fixed the issue in log3, as soon as the pull request is approved it'll be fine.
